import Link from "next/link";
import { audienceGroups, demoContent, demoCreatives, researchPatterns, strategy, trackingChecklist } from "@/lib/campaign-demo-data";
import { contentDetailSlugByFormat } from "@/lib/content-demo-data";
import type { WorkspaceTab } from "@/types/campaign-workspace";
import { Icon } from "@/components/ui/icon";
import { CampaignMetrics } from "./campaign-metrics";
import { WorkspaceStatus } from "./workspace-status";

export function WorkspacePanel({ tab }: { tab: Exclude<WorkspaceTab, "overview"> }) {
  switch (tab) {
    case "research": return <div className="workspace-reading"><section className="panel workspace-document"><h2>Investigación de mercado</h2><p className="workspace-intro">Datos de demostración · Estos patrones son ejemplos, no hallazgos de una investigación real.</p><h3>Principales patrones observados</h3><ul className="workspace-bullets">{researchPatterns.map(pattern => <li key={pattern}>{pattern}</li>)}</ul></section><section className="workspace-callout"><Icon name="spark" size={23} /><div><h3>Oportunidad detectada</h3><p>Posicionar la propuesta alrededor de claridad, progresión y facilidad de aplicación.</p></div></section></div>;
    case "audience": return <><section className="workspace-callout"><Icon name="target" size={24} /><div><h2>Perfil principal</h2><p>Propietarios que buscan mejorar la obediencia básica desde casa.</p></div></section><div className="workspace-three-grid">{audienceGroups.map(group => <section className="panel workspace-document" key={group.title}><h3>{group.title}</h3><ul className="workspace-bullets">{group.items.map(item => <li key={item}>{item}</li>)}</ul></section>)}</div></>;
    case "strategy": return <><div className="workspace-section-heading"><h2>Estrategia de campaña</h2><span className="example-tag">Hipótesis de ejemplo</span></div><dl className="workspace-two-grid">{strategy.map(item => <div className="panel workspace-document" key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></>;
    case "plan": return <><div className="workspace-section-heading"><h2>Plan de contenido</h2><span className="example-tag">2 semanas · Instagram</span></div><div className="workspace-two-grid">{([1, 2] as const).map(week => <section className="panel workspace-week" key={week}><div className="workspace-week-heading"><span className="icon-tile blue"><Icon name="calendar" /></span><div><h3>Semana {week}</h3><p>{week === 1 ? "Conectar y entender" : "Educar y presentar la oferta"}</p></div></div><ol>{demoContent.filter(item => item.week === week).map(item => <li key={item.id}><div><span className="workspace-format">{item.format}</span><WorkspaceStatus value={item.status} /></div><h4>{item.title}</h4></li>)}</ol></section>)}</div></>;
    case "content": return <><div className="workspace-section-heading"><h2>Contenido de campaña</h2><span className="example-tag">6 piezas de ejemplo</span></div><div className="workspace-three-grid">{demoContent.map(item => <article className="panel workspace-content-card" key={item.id}><div className="workspace-content-top"><span className="icon-tile blue"><Icon name={item.format === "Reel" ? "image" : "content"} /></span><WorkspaceStatus value={item.status} /></div><span className="workspace-format">{item.format}</span><h3>{item.title}</h3><dl><dt>Objetivo</dt><dd>{item.objective}</dd><dt>CTA</dt><dd>{item.cta}</dd></dl><Link className="workspace-preview-button" href={`/campaigns/demo/content/${contentDetailSlugByFormat[item.format]}`}>Ver contenido <Icon name="arrow" size={15} /></Link><span className="workspace-preview-note">Contenido de ejemplo · {item.format}</span></article>)}</div></>;
    case "creatives": return <><div className="workspace-section-heading"><h2>Creatividades</h2><span className="example-tag">Maquetas visuales</span></div><p className="workspace-intro">Placeholders de demostración. No hay imágenes generadas ni piezas listas para publicar.</p><div className="workspace-three-grid">{demoCreatives.map(item => <article className="panel workspace-creative" key={item.format}><div className={`creative-placeholder creative-${item.tone}`} aria-hidden="true"><span>impulso.</span><div className="creative-orbit" /><Icon name="spark" size={44} /><strong>{item.title}</strong><span>MÉTODO CANINO EN CASA</span></div><div className="creative-caption"><div><h3>{item.format}</h3><p>{item.size} px</p></div><WorkspaceStatus value={item.status} /></div></article>)}</div><p className="workspace-intro">«Lista» representa un estado ficticio de la maqueta; las creatividades reales siguen pendientes.</p></>;
    case "paid": return <><section className="workspace-callout workspace-warning"><Icon name="target" size={25} /><div><h2>Paid Media · No activado</h2><p>La campaña de Paid Media todavía no está autorizada.</p></div></section><dl className="workspace-two-grid">{[{ label: "Budget", value: "Pendiente de decisión" }, { label: "Objective", value: "Validación inicial" }, { label: "Channels", value: "Meta Ads — pendiente" }, { label: "Estado", value: "No activado" }].map(item => <div className="panel workspace-document" key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></>;
    case "tracking": return <div className="workspace-reading"><section className="panel workspace-document"><h2>Preparación de tracking</h2><p className="workspace-intro">Checklist de ejemplo. Ninguna herramienta está conectada.</p><ul className="workspace-checklist">{trackingChecklist.map(item => <li key={item.label}><span><Icon name={item.status === "Configurado" ? "check" : "settings"} size={18} />{item.label}</span><WorkspaceStatus value={item.status} /></li>)}</ul></section><div className="workspace-callout workspace-warning"><Icon name="chart" size={23} /><div><h3>Tracking todavía no está listo para ejecución.</h3><p>Los estados son mock, incluida la estructura UTM marcada como configurada.</p></div></div></div>;
    case "metrics": return <CampaignMetrics />;
  }
}
