"""add campaign domain persistence

Revision ID: 0977f6691593
Revises: ce93e0b40957
Create Date: 2026-09-08 11:08:22.654035

BACKEND-05: Campaign, Campaign Brief, Campaign Run. Adds three tables
only — no BACKEND-04 identity/tenancy table is touched. See
``downgrade()`` for the explicit native-enum cleanup this migration
needs (the same gotcha documented in the BACKEND-04 migration:
``op.drop_table`` does not drop the Postgres ENUM types a table's
columns implicitly created).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0977f6691593'
down_revision: Union[str, Sequence[str], None] = 'ce93e0b40957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ORCHESTRATING', 'AWAITING_HUMAN_INPUT', 'READY_FOR_EXECUTION', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', 'CANCELLED', name='campaign_status'), server_default='SUBMITTED', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_campaigns_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_public_id'), 'campaigns', ['public_id'], unique=True)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('campaign_briefs',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=60), nullable=True),
    sa.Column('audience', sa.String(length=200), nullable=True),
    sa.Column('budget', sa.String(length=60), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_briefs_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_briefs'))
    )
    op.create_index(op.f('ix_campaign_briefs_campaign_id'), 'campaign_briefs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_briefs_public_id'), 'campaign_briefs', ['public_id'], unique=True)
    op.create_index('uq_campaign_briefs_campaign_version', 'campaign_briefs', ['campaign_id', 'version'], unique=True)
    op.create_table('campaign_runs',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'AWAITING_HUMAN_DECISION', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaign_run_status'), server_default='CREATED', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_runs_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_campaign_runs_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_runs'))
    )
    op.create_index(op.f('ix_campaign_runs_campaign_id'), 'campaign_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_runs_public_id'), 'campaign_runs', ['public_id'], unique=True)
    op.create_index(op.f('ix_campaign_runs_workspace_id'), 'campaign_runs', ['workspace_id'], unique=False)
    op.create_index('uq_campaign_runs_campaign_run_number', 'campaign_runs', ['campaign_id', 'run_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_campaign_runs_campaign_run_number', table_name='campaign_runs')
    op.drop_index(op.f('ix_campaign_runs_workspace_id'), table_name='campaign_runs')
    op.drop_index(op.f('ix_campaign_runs_public_id'), table_name='campaign_runs')
    op.drop_index(op.f('ix_campaign_runs_campaign_id'), table_name='campaign_runs')
    op.drop_table('campaign_runs')
    op.drop_index('uq_campaign_briefs_campaign_version', table_name='campaign_briefs')
    op.drop_index(op.f('ix_campaign_briefs_public_id'), table_name='campaign_briefs')
    op.drop_index(op.f('ix_campaign_briefs_campaign_id'), table_name='campaign_briefs')
    op.drop_table('campaign_briefs')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_public_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
    # `op.drop_table` above does not drop the native Postgres ENUM types
    # these tables' columns implicitly created — without this, a
    # downgrade-then-upgrade round trip fails with
    # `DuplicateObject: type "campaign_status" already exists` (the
    # exact bug found and fixed during BACKEND-04's migration; see
    # ce93e0b40957's downgrade() for the precedent).
    sa.Enum(name="campaign_run_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="campaign_status").drop(op.get_bind(), checkfirst=True)
