"""add orchestration foundation

Revision ID: 0bb72567beac
Revises: 0977f6691593
Create Date: 2026-09-08 12:06:25.249476

BACKEND-06: RunStageExecution, HumanDecisionRequest, HumanDecisionResponse,
AuditEvent — plus the BACKEND-06 §6 tenancy invariant hardening on the
existing BACKEND-05 tables: a composite unique key on
``campaigns (id, workspace_id)`` and a composite foreign key from
``campaign_runs (campaign_id, workspace_id)`` replacing the old
single-column FK, so Postgres itself rejects a CampaignRun whose
workspace diverges from its Campaign's. No BACKEND-04/05 table is
otherwise touched. See ``downgrade()`` for the explicit native-enum
cleanup this migration needs (the same gotcha fixed in BACKEND-04's and
BACKEND-05's own migrations: ``op.drop_table`` does not drop the
Postgres ENUM types a table's columns implicitly created).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb72567beac'
down_revision: Union[str, Sequence[str], None] = '0977f6691593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_stage_executions',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('RESEARCH', 'AUDIENCE', 'STRATEGY', 'PLAN', 'CONTENT', 'CREATIVE', 'DISTRIBUTION', 'PAID_MEDIA', 'TRACKING', 'MEASUREMENT', 'LEARNING', name='business_stage'), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'RUNNING', 'WAITING_FOR_INPUT', 'BLOCKED', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', name='stage_execution_status'), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_run_id'], ['campaign_runs.id'], name=op.f('fk_run_stage_executions_campaign_run_id_campaign_runs')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_run_stage_executions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_stage_executions'))
    )
    op.create_index(op.f('ix_run_stage_executions_campaign_run_id'), 'run_stage_executions', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_run_stage_executions_public_id'), 'run_stage_executions', ['public_id'], unique=True)
    op.create_index(op.f('ix_run_stage_executions_workspace_id'), 'run_stage_executions', ['workspace_id'], unique=False)
    op.create_index('uq_run_stage_executions_run_ordinal', 'run_stage_executions', ['campaign_run_id', 'ordinal'], unique=True)
    op.create_index('uq_run_stage_executions_run_stage', 'run_stage_executions', ['campaign_run_id', 'stage'], unique=True)
    op.create_table('audit_events',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=True),
    sa.Column('stage_execution_id', sa.Uuid(), nullable=True),
    sa.Column('decision_request_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=100), nullable=True),
    sa.Column('new_state', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'AGENT', name='audit_actor_type'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_audit_events_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['campaign_run_id'], ['campaign_runs.id'], name=op.f('fk_audit_events_campaign_run_id_campaign_runs')),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['run_stage_executions.id'], name=op.f('fk_audit_events_stage_execution_id_run_stage_executions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_campaign_id'), 'audit_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_audit_events_campaign_run_id'), 'audit_events', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_decision_request_id'), 'audit_events', ['decision_request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_public_id'), 'audit_events', ['public_id'], unique=True)
    op.create_index(op.f('ix_audit_events_stage_execution_id'), 'audit_events', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('human_decision_requests',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_execution_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'EXPIRED', 'CANCELLED', name='decision_request_status'), server_default='OPEN', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_run_id'], ['campaign_runs.id'], name=op.f('fk_human_decision_requests_campaign_run_id_campaign_runs')),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['run_stage_executions.id'], name=op.f('fk_human_decision_requests_stage_execution_id_run_stage_executions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_human_decision_requests_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_decision_requests'))
    )
    op.create_index(op.f('ix_human_decision_requests_campaign_run_id'), 'human_decision_requests', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_human_decision_requests_public_id'), 'human_decision_requests', ['public_id'], unique=True)
    op.create_index(op.f('ix_human_decision_requests_stage_execution_id'), 'human_decision_requests', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_human_decision_requests_workspace_id'), 'human_decision_requests', ['workspace_id'], unique=False)
    # audit_events.decision_request_id's FK target (human_decision_requests)
    # did not exist yet when audit_events was created above, so it is
    # added here as a separate step (BACKEND-06R: added after the fact to
    # let a decision-related Audit Event be attributed to the specific
    # HumanDecisionRequest it is about).
    op.create_foreign_key(
        'fk_audit_events_decision_request_id_human_decision_requests',
        'audit_events', 'human_decision_requests', ['decision_request_id'], ['id'],
    )
    op.create_table('human_decision_responses',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('decision_request_id', sa.Uuid(), nullable=False),
    sa.Column('responded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['human_decision_requests.id'], name=op.f('fk_human_decision_responses_decision_request_id_human_decision_requests')),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], name=op.f('fk_human_decision_responses_responded_by_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_human_decision_responses_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_decision_responses'))
    )
    op.create_index(op.f('ix_human_decision_responses_decision_request_id'), 'human_decision_responses', ['decision_request_id'], unique=False)
    op.create_index(op.f('ix_human_decision_responses_public_id'), 'human_decision_responses', ['public_id'], unique=True)
    op.create_index(op.f('ix_human_decision_responses_responded_by_user_id'), 'human_decision_responses', ['responded_by_user_id'], unique=False)
    op.create_index(op.f('ix_human_decision_responses_workspace_id'), 'human_decision_responses', ['workspace_id'], unique=False)
    op.create_index('uq_human_decision_responses_request', 'human_decision_responses', ['decision_request_id'], unique=True)
    op.drop_constraint(op.f('fk_campaign_runs_campaign_id_campaigns'), 'campaign_runs', type_='foreignkey')
    # Autogenerate ordered this after the composite FK below; the FK
    # target must exist first, so the unique constraint is created here,
    # before create_foreign_key (manually reordered from the raw
    # autogenerate output).
    op.create_unique_constraint('uq_campaigns_id_workspace_id', 'campaigns', ['id', 'workspace_id'])
    op.create_foreign_key('fk_campaign_runs_campaign_workspace', 'campaign_runs', 'campaigns', ['campaign_id', 'workspace_id'], ['id', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually reordered from the raw autogenerate output: the composite
    # FK must be dropped *before* the unique constraint it depends on —
    # Postgres refuses to drop a unique constraint still referenced by a
    # live foreign key.
    op.drop_constraint('fk_campaign_runs_campaign_workspace', 'campaign_runs', type_='foreignkey')
    op.drop_constraint('uq_campaigns_id_workspace_id', 'campaigns', type_='unique')
    op.create_foreign_key(op.f('fk_campaign_runs_campaign_id_campaigns'), 'campaign_runs', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index('uq_human_decision_responses_request', table_name='human_decision_responses')
    op.drop_index(op.f('ix_human_decision_responses_workspace_id'), table_name='human_decision_responses')
    op.drop_index(op.f('ix_human_decision_responses_responded_by_user_id'), table_name='human_decision_responses')
    op.drop_index(op.f('ix_human_decision_responses_public_id'), table_name='human_decision_responses')
    op.drop_index(op.f('ix_human_decision_responses_decision_request_id'), table_name='human_decision_responses')
    op.drop_table('human_decision_responses')
    # Must be dropped before human_decision_requests itself — Postgres
    # refuses to drop a table that a live foreign key (audit_events.
    # decision_request_id) still references.
    op.drop_constraint(
        'fk_audit_events_decision_request_id_human_decision_requests', 'audit_events', type_='foreignkey'
    )
    op.drop_index(op.f('ix_human_decision_requests_workspace_id'), table_name='human_decision_requests')
    op.drop_index(op.f('ix_human_decision_requests_stage_execution_id'), table_name='human_decision_requests')
    op.drop_index(op.f('ix_human_decision_requests_public_id'), table_name='human_decision_requests')
    op.drop_index(op.f('ix_human_decision_requests_campaign_run_id'), table_name='human_decision_requests')
    op.drop_table('human_decision_requests')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_stage_execution_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_decision_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_public_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_campaign_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_campaign_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('uq_run_stage_executions_run_stage', table_name='run_stage_executions')
    op.drop_index('uq_run_stage_executions_run_ordinal', table_name='run_stage_executions')
    op.drop_index(op.f('ix_run_stage_executions_workspace_id'), table_name='run_stage_executions')
    op.drop_index(op.f('ix_run_stage_executions_public_id'), table_name='run_stage_executions')
    op.drop_index(op.f('ix_run_stage_executions_campaign_run_id'), table_name='run_stage_executions')
    op.drop_table('run_stage_executions')
    # ### end Alembic commands ###
    # `op.drop_table` above does not drop the native Postgres ENUM types
    # these tables' columns implicitly created — without this, a
    # downgrade-then-upgrade round trip fails with
    # `DuplicateObject: type "..." already exists` (see ce93e0b40957's
    # and 0977f6691593's downgrade() for the precedent this repeats).
    sa.Enum(name="decision_request_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="audit_actor_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="stage_execution_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="business_stage").drop(op.get_bind(), checkfirst=True)
