"""add learning persistence

Revision ID: 448a7fa7936d
Revises: 8e43d97d836c
Create Date: 2026-09-10 13:09:03.032615

`op.drop_table('strategic_recommendation_candidates'/'learning_candidates')`
below does not drop the native Postgres ENUM types those columns
implicitly created — without the explicit drops at the end of
downgrade(), a downgrade-then-upgrade round trip fails with
`DuplicateObject: type "..." already exists` (the same gotcha fixed in
every prior migration in this project with a native enum — see
654d662d78e7's own downgrade() for `metric_source`).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448a7fa7936d'
down_revision: Union[str, Sequence[str], None] = '8e43d97d836c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_candidates',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_result_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE_IDENTIFIED', 'PROVISIONAL', 'VALIDATION_PENDING', 'VALIDATED', 'REJECTED', 'INSUFFICIENT_EVIDENCE', name='learning_candidate_status'), server_default='CANDIDATE_IDENTIFIED', nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id', 'workspace_id'], ['analysis_results.id', 'analysis_results.workspace_id'], name='fk_learning_candidates_analysis_result_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_learning_candidates_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_candidates')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_learning_candidates_id_workspace_id')
    )
    op.create_index(op.f('ix_learning_candidates_analysis_result_id'), 'learning_candidates', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_learning_candidates_public_id'), 'learning_candidates', ['public_id'], unique=True)
    op.create_index(op.f('ix_learning_candidates_workspace_id'), 'learning_candidates', ['workspace_id'], unique=False)
    op.create_table('strategic_recommendation_candidates',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('learning_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPTED', 'REJECTED', name='strategic_recommendation_decision'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['learning_candidate_id', 'workspace_id'], ['learning_candidates.id', 'learning_candidates.workspace_id'], name='fk_strategic_recommendation_candidates_learning_candidate_ws'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_strategic_recommendation_candidates_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategic_recommendation_candidates'))
    )
    op.create_index(op.f('ix_strategic_recommendation_candidates_learning_candidate_id'), 'strategic_recommendation_candidates', ['learning_candidate_id'], unique=False)
    op.create_index(op.f('ix_strategic_recommendation_candidates_public_id'), 'strategic_recommendation_candidates', ['public_id'], unique=True)
    op.create_index(op.f('ix_strategic_recommendation_candidates_workspace_id'), 'strategic_recommendation_candidates', ['workspace_id'], unique=False)
    op.add_column('audit_events', sa.Column('learning_candidate_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('strategic_recommendation_candidate_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_learning_candidate_id'), 'audit_events', ['learning_candidate_id'], unique=False)
    op.create_index(op.f('ix_audit_events_strategic_recommendation_candidate_id'), 'audit_events', ['strategic_recommendation_candidate_id'], unique=False)
    op.create_foreign_key('fk_audit_events_strategic_recommendation_candidate_id_src', 'audit_events', 'strategic_recommendation_candidates', ['strategic_recommendation_candidate_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_learning_candidate_id_learning_candidates'), 'audit_events', 'learning_candidates', ['learning_candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_events_learning_candidate_id_learning_candidates'), 'audit_events', type_='foreignkey')
    op.drop_constraint('fk_audit_events_strategic_recommendation_candidate_id_src', 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_strategic_recommendation_candidate_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_learning_candidate_id'), table_name='audit_events')
    op.drop_column('audit_events', 'strategic_recommendation_candidate_id')
    op.drop_column('audit_events', 'learning_candidate_id')
    op.drop_index(op.f('ix_strategic_recommendation_candidates_workspace_id'), table_name='strategic_recommendation_candidates')
    op.drop_index(op.f('ix_strategic_recommendation_candidates_public_id'), table_name='strategic_recommendation_candidates')
    op.drop_index(op.f('ix_strategic_recommendation_candidates_learning_candidate_id'), table_name='strategic_recommendation_candidates')
    op.drop_table('strategic_recommendation_candidates')
    op.drop_index(op.f('ix_learning_candidates_workspace_id'), table_name='learning_candidates')
    op.drop_index(op.f('ix_learning_candidates_public_id'), table_name='learning_candidates')
    op.drop_index(op.f('ix_learning_candidates_analysis_result_id'), table_name='learning_candidates')
    op.drop_table('learning_candidates')
    # ### end Alembic commands ###
    sa.Enum(name="strategic_recommendation_decision").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="learning_candidate_status").drop(op.get_bind(), checkfirst=True)
