"""add research and audience persistence

Revision ID: 4b9a72f05a4f
Revises: 0bb72567beac
Create Date: 2026-09-08 15:02:39.480267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9a72f05a4f'
down_revision: Union[str, Sequence[str], None] = '0bb72567beac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually reordered from the raw autogenerate output: this
    # candidate key must exist *before* research_reports/audience_profiles
    # can declare a composite FK against campaign_runs(id, workspace_id)
    # below (autogenerate placed it last; Postgres needs it first).
    op.create_unique_constraint('uq_campaign_runs_id_workspace_id', 'campaign_runs', ['id', 'workspace_id'])
    op.create_table('audience_profiles',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_execution_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_audience_profiles_campaign_workspace'),
    sa.ForeignKeyConstraint(['campaign_run_id', 'workspace_id'], ['campaign_runs.id', 'campaign_runs.workspace_id'], name='fk_audience_profiles_campaign_run_workspace'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['run_stage_executions.id'], name=op.f('fk_audience_profiles_stage_execution_id_run_stage_executions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audience_profiles_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_profiles')),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_audience_profiles_campaign_version')
    )
    op.create_index(op.f('ix_audience_profiles_campaign_id'), 'audience_profiles', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_audience_profiles_campaign_run_id'), 'audience_profiles', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_audience_profiles_public_id'), 'audience_profiles', ['public_id'], unique=True)
    op.create_index(op.f('ix_audience_profiles_stage_execution_id'), 'audience_profiles', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_audience_profiles_workspace_id'), 'audience_profiles', ['workspace_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_execution_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_research_reports_campaign_workspace'),
    sa.ForeignKeyConstraint(['campaign_run_id', 'workspace_id'], ['campaign_runs.id', 'campaign_runs.workspace_id'], name='fk_research_reports_campaign_run_workspace'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['run_stage_executions.id'], name=op.f('fk_research_reports_stage_execution_id_run_stage_executions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_reports_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_reports')),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_research_reports_campaign_version')
    )
    op.create_index(op.f('ix_research_reports_campaign_id'), 'research_reports', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_research_reports_campaign_run_id'), 'research_reports', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_research_reports_public_id'), 'research_reports', ['public_id'], unique=True)
    op.create_index(op.f('ix_research_reports_stage_execution_id'), 'research_reports', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_research_reports_workspace_id'), 'research_reports', ['workspace_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('research_report_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('ARTICLE', 'REPORT', 'FORUM', 'SOCIAL', 'SURVEY', 'OTHER', name='source_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('locator', sa.String(length=2000), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('excerpt', sa.String(length=2000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['research_report_id'], ['research_reports.id'], name=op.f('fk_research_sources_research_report_id_research_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources'))
    )
    op.create_index(op.f('ix_research_sources_public_id'), 'research_sources', ['public_id'], unique=True)
    op.create_index(op.f('ix_research_sources_research_report_id'), 'research_sources', ['research_report_id'], unique=False)
    op.create_table('voc_evidence',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('audience_profile_id', sa.Uuid(), nullable=False),
    sa.Column('verbatim_quote', sa.String(length=4000), nullable=True),
    sa.Column('paraphrase', sa.String(length=4000), nullable=True),
    sa.Column('source_type', sa.Enum('ARTICLE', 'REPORT', 'FORUM', 'SOCIAL', 'SURVEY', 'OTHER', name='source_type'), nullable=True),
    sa.Column('source_locator', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('verbatim_quote IS NOT NULL OR paraphrase IS NOT NULL', name=op.f('ck_voc_evidence_quote_or_paraphrase')),
    sa.ForeignKeyConstraint(['audience_profile_id'], ['audience_profiles.id'], name=op.f('fk_voc_evidence_audience_profile_id_audience_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voc_evidence'))
    )
    op.create_index(op.f('ix_voc_evidence_audience_profile_id'), 'voc_evidence', ['audience_profile_id'], unique=False)
    op.create_index(op.f('ix_voc_evidence_public_id'), 'voc_evidence', ['public_id'], unique=True)
    op.add_column('audit_events', sa.Column('research_report_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('audience_profile_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_audience_profile_id'), 'audit_events', ['audience_profile_id'], unique=False)
    op.create_index(op.f('ix_audit_events_research_report_id'), 'audit_events', ['research_report_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_audience_profile_id_audience_profiles'), 'audit_events', 'audience_profiles', ['audience_profile_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_research_report_id_research_reports'), 'audit_events', 'research_reports', ['research_report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually reordered: the campaign_runs candidate key is dropped at
    # the very end (below), only after research_reports/audience_profiles
    # — whose composite FKs reference it — are already gone; Postgres
    # refuses to drop a unique constraint still referenced by a live FK.
    op.drop_constraint(op.f('fk_audit_events_research_report_id_research_reports'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_audience_profile_id_audience_profiles'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_research_report_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_audience_profile_id'), table_name='audit_events')
    op.drop_column('audit_events', 'audience_profile_id')
    op.drop_column('audit_events', 'research_report_id')
    op.drop_index(op.f('ix_voc_evidence_public_id'), table_name='voc_evidence')
    op.drop_index(op.f('ix_voc_evidence_audience_profile_id'), table_name='voc_evidence')
    op.drop_table('voc_evidence')
    op.drop_index(op.f('ix_research_sources_research_report_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_public_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_reports_workspace_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_stage_execution_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_public_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_campaign_run_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_campaign_id'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_audience_profiles_workspace_id'), table_name='audience_profiles')
    op.drop_index(op.f('ix_audience_profiles_stage_execution_id'), table_name='audience_profiles')
    op.drop_index(op.f('ix_audience_profiles_public_id'), table_name='audience_profiles')
    op.drop_index(op.f('ix_audience_profiles_campaign_run_id'), table_name='audience_profiles')
    op.drop_index(op.f('ix_audience_profiles_campaign_id'), table_name='audience_profiles')
    op.drop_table('audience_profiles')
    # campaign_runs candidate key: dropped last, now that nothing
    # references it any more (see the note at the top of this function).
    op.drop_constraint('uq_campaign_runs_id_workspace_id', 'campaign_runs', type_='unique')
    # ### end Alembic commands ###
    # `op.drop_table` above does not drop the native Postgres ENUM type
    # `source_type` these tables' columns implicitly created — without
    # this, a downgrade-then-upgrade round trip fails with
    # `DuplicateObject: type "source_type" already exists` (the same
    # gotcha fixed in every prior migration in this project — see
    # ce93e0b40957/0977f6691593/0bb72567beac's own downgrade()).
    sa.Enum(name="source_type").drop(op.get_bind(), checkfirst=True)
