"""add learning derivation table

Revision ID: 59405cfacd5a
Revises: 1c5dd0290557
Create Date: 2026-09-13 13:48:39.646931

MVP-12B-A/-R1: purely additive. One new table, ``learning_derivations``,
is created to give the explicit Measurement -> Learning bridge its own
concurrency-safe identity (``UNIQUE(analysis_result_id)``,
``UNIQUE(learning_candidate_id)``), without altering ``learning_candidates``
or ``analysis_results`` at all — neither table's schema, columns, or
existing constraints change. No native enum type is introduced.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59405cfacd5a'
down_revision: Union[str, Sequence[str], None] = '1c5dd0290557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_derivations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_result_id', sa.Uuid(), nullable=False),
    sa.Column('learning_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id', 'workspace_id'], ['analysis_results.id', 'analysis_results.workspace_id'], name='fk_learning_derivations_analysis_result_workspace'),
    sa.ForeignKeyConstraint(['learning_candidate_id', 'workspace_id'], ['learning_candidates.id', 'learning_candidates.workspace_id'], name='fk_learning_derivations_learning_candidate_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_learning_derivations_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_derivations')),
    sa.UniqueConstraint('analysis_result_id', name='uq_learning_derivations_analysis_result_id'),
    sa.UniqueConstraint('learning_candidate_id', name='uq_learning_derivations_learning_candidate_id')
    )
    op.create_index(op.f('ix_learning_derivations_analysis_result_id'), 'learning_derivations', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_learning_derivations_learning_candidate_id'), 'learning_derivations', ['learning_candidate_id'], unique=False)
    op.create_index(op.f('ix_learning_derivations_workspace_id'), 'learning_derivations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_derivations_workspace_id'), table_name='learning_derivations')
    op.drop_index(op.f('ix_learning_derivations_learning_candidate_id'), table_name='learning_derivations')
    op.drop_index(op.f('ix_learning_derivations_analysis_result_id'), table_name='learning_derivations')
    op.drop_table('learning_derivations')
    # ### end Alembic commands ###
