"""add planning persistence

Revision ID: 5a6a04e3776d
Revises: 5e50463be153
Create Date: 2026-09-08 17:02:38.145507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6a04e3776d'
down_revision: Union[str, Sequence[str], None] = '5e50463be153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_plans',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_execution_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_content_plans_campaign_workspace'),
    sa.ForeignKeyConstraint(['campaign_run_id', 'workspace_id'], ['campaign_runs.id', 'campaign_runs.workspace_id'], name='fk_content_plans_campaign_run_workspace'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['run_stage_executions.id'], name=op.f('fk_content_plans_stage_execution_id_run_stage_executions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_plans_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_plans')),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_content_plans_campaign_version')
    )
    op.create_index(op.f('ix_content_plans_campaign_id'), 'content_plans', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_plans_campaign_run_id'), 'content_plans', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_content_plans_public_id'), 'content_plans', ['public_id'], unique=True)
    op.create_index(op.f('ix_content_plans_stage_execution_id'), 'content_plans', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_content_plans_workspace_id'), 'content_plans', ['workspace_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('content_plan_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.String(length=1000), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_plan_id'], ['content_plans.id'], name=op.f('fk_plan_items_content_plan_id_content_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items'))
    )
    op.create_index(op.f('ix_plan_items_content_plan_id'), 'plan_items', ['content_plan_id'], unique=False)
    op.create_index(op.f('ix_plan_items_public_id'), 'plan_items', ['public_id'], unique=True)
    op.add_column('audit_events', sa.Column('content_plan_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('plan_item_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_content_plan_id'), 'audit_events', ['content_plan_id'], unique=False)
    op.create_index(op.f('ix_audit_events_plan_item_id'), 'audit_events', ['plan_item_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_content_plan_id_content_plans'), 'audit_events', 'content_plans', ['content_plan_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_plan_item_id_plan_items'), 'audit_events', 'plan_items', ['plan_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_events_plan_item_id_plan_items'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_content_plan_id_content_plans'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_plan_item_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_content_plan_id'), table_name='audit_events')
    op.drop_column('audit_events', 'plan_item_id')
    op.drop_column('audit_events', 'content_plan_id')
    op.drop_index(op.f('ix_plan_items_public_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_content_plan_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_content_plans_workspace_id'), table_name='content_plans')
    op.drop_index(op.f('ix_content_plans_stage_execution_id'), table_name='content_plans')
    op.drop_index(op.f('ix_content_plans_public_id'), table_name='content_plans')
    op.drop_index(op.f('ix_content_plans_campaign_run_id'), table_name='content_plans')
    op.drop_index(op.f('ix_content_plans_campaign_id'), table_name='content_plans')
    op.drop_table('content_plans')
    # ### end Alembic commands ###
