"""add strategy persistence

Revision ID: 5e50463be153
Revises: 4b9a72f05a4f
Create Date: 2026-09-08 16:01:58.906945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e50463be153'
down_revision: Union[str, Sequence[str], None] = '4b9a72f05a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_execution_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_strategies_campaign_workspace'),
    sa.ForeignKeyConstraint(['campaign_run_id', 'workspace_id'], ['campaign_runs.id', 'campaign_runs.workspace_id'], name='fk_strategies_campaign_run_workspace'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['run_stage_executions.id'], name=op.f('fk_strategies_stage_execution_id_run_stage_executions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_strategies_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_strategies_campaign_version'),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_strategies_id_workspace_id')
    )
    op.create_index(op.f('ix_strategies_campaign_id'), 'strategies', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_strategies_campaign_run_id'), 'strategies', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_strategies_public_id'), 'strategies', ['public_id'], unique=True)
    op.create_index(op.f('ix_strategies_stage_execution_id'), 'strategies', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_strategies_workspace_id'), 'strategies', ['workspace_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONFIRMED', 'REFUTED', name='hypothesis_status'), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id', 'workspace_id'], ['strategies.id', 'strategies.workspace_id'], name='fk_hypotheses_strategy_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_hypotheses_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_hypotheses_id_workspace_id')
    )
    op.create_index(op.f('ix_hypotheses_public_id'), 'hypotheses', ['public_id'], unique=True)
    op.create_index(op.f('ix_hypotheses_strategy_id'), 'hypotheses', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_workspace_id'), 'hypotheses', ['workspace_id'], unique=False)
    op.create_table('positionings',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_positionings_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positionings'))
    )
    op.create_index(op.f('ix_positionings_public_id'), 'positionings', ['public_id'], unique=True)
    op.create_index(op.f('ix_positionings_strategy_id'), 'positionings', ['strategy_id'], unique=True)
    op.create_table('experiments',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id', 'workspace_id'], ['hypotheses.id', 'hypotheses.workspace_id'], name='fk_experiments_hypothesis_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_experiments_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_hypothesis_id'), 'experiments', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_experiments_public_id'), 'experiments', ['public_id'], unique=True)
    op.create_index(op.f('ix_experiments_workspace_id'), 'experiments', ['workspace_id'], unique=False)
    op.add_column('audit_events', sa.Column('strategy_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('hypothesis_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('experiment_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_experiment_id'), 'audit_events', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_audit_events_hypothesis_id'), 'audit_events', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_audit_events_strategy_id'), 'audit_events', ['strategy_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_experiment_id_experiments'), 'audit_events', 'experiments', ['experiment_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_strategy_id_strategies'), 'audit_events', 'strategies', ['strategy_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_hypothesis_id_hypotheses'), 'audit_events', 'hypotheses', ['hypothesis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_events_hypothesis_id_hypotheses'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_strategy_id_strategies'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_experiment_id_experiments'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_strategy_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_hypothesis_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_experiment_id'), table_name='audit_events')
    op.drop_column('audit_events', 'experiment_id')
    op.drop_column('audit_events', 'hypothesis_id')
    op.drop_column('audit_events', 'strategy_id')
    op.drop_index(op.f('ix_experiments_workspace_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_public_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_hypothesis_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_positionings_strategy_id'), table_name='positionings')
    op.drop_index(op.f('ix_positionings_public_id'), table_name='positionings')
    op.drop_table('positionings')
    op.drop_index(op.f('ix_hypotheses_workspace_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_strategy_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_public_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_strategies_workspace_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_stage_execution_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_public_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_campaign_run_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_campaign_id'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
    # `op.drop_table('hypotheses')` above does not drop the native
    # Postgres ENUM type `hypothesis_status` that column implicitly
    # created — without this, a downgrade-then-upgrade round trip fails
    # with `DuplicateObject: type "hypothesis_status" already exists`
    # (the same gotcha fixed in every prior migration in this project —
    # see 4b9a72f05a4f's own downgrade() for `source_type`).
    sa.Enum(name="hypothesis_status").drop(op.get_bind(), checkfirst=True)
