"""add measurement persistence

Revision ID: 654d662d78e7
Revises: acaad5704928
Create Date: 2026-09-09 12:40:45.992699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654d662d78e7'
down_revision: Union[str, Sequence[str], None] = 'acaad5704928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_analysis_results_campaign_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_analysis_results_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_analysis_results_id_workspace_id')
    )
    op.create_index(op.f('ix_analysis_results_campaign_id'), 'analysis_results', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_public_id'), 'analysis_results', ['public_id'], unique=True)
    op.create_index(op.f('ix_analysis_results_workspace_id'), 'analysis_results', ['workspace_id'], unique=False)
    op.create_table('metric_entries',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'IMPORTED', 'PLATFORM', name='metric_source'), nullable=False),
    sa.Column('client_request_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_metric_entries_period_end_after_start')),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_metric_entries_campaign_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_metric_entries_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_entries')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_metric_entries_id_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'client_request_id', name='uq_metric_entries_workspace_client_request_id')
    )
    op.create_index(op.f('ix_metric_entries_campaign_id'), 'metric_entries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_metric_entries_public_id'), 'metric_entries', ['public_id'], unique=True)
    op.create_index(op.f('ix_metric_entries_workspace_id'), 'metric_entries', ['workspace_id'], unique=False)
    op.create_table('performance_observations',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_performance_observations_campaign_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_performance_observations_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_observations')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_performance_observations_id_workspace_id')
    )
    op.create_index(op.f('ix_performance_observations_campaign_id'), 'performance_observations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_performance_observations_public_id'), 'performance_observations', ['public_id'], unique=True)
    op.create_index(op.f('ix_performance_observations_workspace_id'), 'performance_observations', ['workspace_id'], unique=False)
    op.create_table('performance_signals',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_performance_signals_campaign_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_performance_signals_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_signals')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_performance_signals_id_workspace_id')
    )
    op.create_index(op.f('ix_performance_signals_campaign_id'), 'performance_signals', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_performance_signals_public_id'), 'performance_signals', ['public_id'], unique=True)
    op.create_index(op.f('ix_performance_signals_workspace_id'), 'performance_signals', ['workspace_id'], unique=False)
    op.create_table('analysis_result_signals',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_result_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id', 'workspace_id'], ['analysis_results.id', 'analysis_results.workspace_id'], name='fk_analysis_result_signals_analysis_result_workspace'),
    sa.ForeignKeyConstraint(['signal_id', 'workspace_id'], ['performance_signals.id', 'performance_signals.workspace_id'], name='fk_analysis_result_signals_signal_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_analysis_result_signals_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_result_signals')),
    sa.UniqueConstraint('analysis_result_id', 'signal_id', name='uq_analysis_result_signals_pair')
    )
    op.create_index(op.f('ix_analysis_result_signals_analysis_result_id'), 'analysis_result_signals', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_analysis_result_signals_signal_id'), 'analysis_result_signals', ['signal_id'], unique=False)
    op.create_index(op.f('ix_analysis_result_signals_workspace_id'), 'analysis_result_signals', ['workspace_id'], unique=False)
    op.create_table('metric_values',
    sa.Column('metric_entry_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['metric_entry_id'], ['metric_entries.id'], name=op.f('fk_metric_values_metric_entry_id_metric_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_values'))
    )
    op.create_index(op.f('ix_metric_values_metric_entry_id'), 'metric_values', ['metric_entry_id'], unique=False)
    op.create_table('observation_metric_entries',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('metric_entry_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['metric_entry_id', 'workspace_id'], ['metric_entries.id', 'metric_entries.workspace_id'], name='fk_observation_metric_entries_metric_entry_workspace'),
    sa.ForeignKeyConstraint(['observation_id', 'workspace_id'], ['performance_observations.id', 'performance_observations.workspace_id'], name='fk_observation_metric_entries_observation_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_observation_metric_entries_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_metric_entries')),
    sa.UniqueConstraint('observation_id', 'metric_entry_id', name='uq_observation_metric_entries_pair')
    )
    op.create_index(op.f('ix_observation_metric_entries_metric_entry_id'), 'observation_metric_entries', ['metric_entry_id'], unique=False)
    op.create_index(op.f('ix_observation_metric_entries_observation_id'), 'observation_metric_entries', ['observation_id'], unique=False)
    op.create_index(op.f('ix_observation_metric_entries_workspace_id'), 'observation_metric_entries', ['workspace_id'], unique=False)
    op.create_table('signal_observations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id', 'workspace_id'], ['performance_observations.id', 'performance_observations.workspace_id'], name='fk_signal_observations_observation_workspace'),
    sa.ForeignKeyConstraint(['signal_id', 'workspace_id'], ['performance_signals.id', 'performance_signals.workspace_id'], name='fk_signal_observations_signal_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_signal_observations_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_observations')),
    sa.UniqueConstraint('signal_id', 'observation_id', name='uq_signal_observations_pair')
    )
    op.create_index(op.f('ix_signal_observations_observation_id'), 'signal_observations', ['observation_id'], unique=False)
    op.create_index(op.f('ix_signal_observations_signal_id'), 'signal_observations', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_observations_workspace_id'), 'signal_observations', ['workspace_id'], unique=False)
    op.add_column('audit_events', sa.Column('metric_entry_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('performance_observation_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('performance_signal_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('analysis_result_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_analysis_result_id'), 'audit_events', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_audit_events_metric_entry_id'), 'audit_events', ['metric_entry_id'], unique=False)
    op.create_index(op.f('ix_audit_events_performance_observation_id'), 'audit_events', ['performance_observation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_performance_signal_id'), 'audit_events', ['performance_signal_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_performance_signal_id_performance_signals'), 'audit_events', 'performance_signals', ['performance_signal_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_analysis_result_id_analysis_results'), 'audit_events', 'analysis_results', ['analysis_result_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_performance_observation_id_performance_observations'), 'audit_events', 'performance_observations', ['performance_observation_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_metric_entry_id_metric_entries'), 'audit_events', 'metric_entries', ['metric_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_events_metric_entry_id_metric_entries'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_performance_observation_id_performance_observations'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_analysis_result_id_analysis_results'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_performance_signal_id_performance_signals'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_performance_signal_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_performance_observation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_metric_entry_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_analysis_result_id'), table_name='audit_events')
    op.drop_column('audit_events', 'analysis_result_id')
    op.drop_column('audit_events', 'performance_signal_id')
    op.drop_column('audit_events', 'performance_observation_id')
    op.drop_column('audit_events', 'metric_entry_id')
    op.drop_index(op.f('ix_signal_observations_workspace_id'), table_name='signal_observations')
    op.drop_index(op.f('ix_signal_observations_signal_id'), table_name='signal_observations')
    op.drop_index(op.f('ix_signal_observations_observation_id'), table_name='signal_observations')
    op.drop_table('signal_observations')
    op.drop_index(op.f('ix_observation_metric_entries_workspace_id'), table_name='observation_metric_entries')
    op.drop_index(op.f('ix_observation_metric_entries_observation_id'), table_name='observation_metric_entries')
    op.drop_index(op.f('ix_observation_metric_entries_metric_entry_id'), table_name='observation_metric_entries')
    op.drop_table('observation_metric_entries')
    op.drop_index(op.f('ix_metric_values_metric_entry_id'), table_name='metric_values')
    op.drop_table('metric_values')
    op.drop_index(op.f('ix_analysis_result_signals_workspace_id'), table_name='analysis_result_signals')
    op.drop_index(op.f('ix_analysis_result_signals_signal_id'), table_name='analysis_result_signals')
    op.drop_index(op.f('ix_analysis_result_signals_analysis_result_id'), table_name='analysis_result_signals')
    op.drop_table('analysis_result_signals')
    op.drop_index(op.f('ix_performance_signals_workspace_id'), table_name='performance_signals')
    op.drop_index(op.f('ix_performance_signals_public_id'), table_name='performance_signals')
    op.drop_index(op.f('ix_performance_signals_campaign_id'), table_name='performance_signals')
    op.drop_table('performance_signals')
    op.drop_index(op.f('ix_performance_observations_workspace_id'), table_name='performance_observations')
    op.drop_index(op.f('ix_performance_observations_public_id'), table_name='performance_observations')
    op.drop_index(op.f('ix_performance_observations_campaign_id'), table_name='performance_observations')
    op.drop_table('performance_observations')
    op.drop_index(op.f('ix_metric_entries_workspace_id'), table_name='metric_entries')
    op.drop_index(op.f('ix_metric_entries_public_id'), table_name='metric_entries')
    op.drop_index(op.f('ix_metric_entries_campaign_id'), table_name='metric_entries')
    op.drop_table('metric_entries')
    op.drop_index(op.f('ix_analysis_results_workspace_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_public_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_campaign_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
    # `op.drop_table('metric_entries')` above does not drop the native
    # Postgres ENUM type `metric_source` that column implicitly created —
    # without this, a downgrade-then-upgrade round trip fails with
    # `DuplicateObject: type "metric_source" already exists` (the same
    # gotcha fixed in every prior migration in this project — see
    # 5e50463be153's own downgrade() for `hypothesis_status`).
    sa.Enum(name="metric_source").drop(op.get_bind(), checkfirst=True)
