"""add content persistence

Revision ID: acaad5704928
Revises: 5a6a04e3776d
Create Date: 2026-09-09 10:37:41.723494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaad5704928'
down_revision: Union[str, Sequence[str], None] = '5a6a04e3776d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Moved ahead of `content_briefs` creation (autogenerate placed it
    # last, but content_briefs' composite FK on
    # (content_plan_id, workspace_id) requires this candidate key to
    # already exist on content_plans first).
    op.create_unique_constraint('uq_content_plans_id_workspace_id', 'content_plans', ['id', 'workspace_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_briefs',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plan_item_id', sa.Uuid(), nullable=False),
    sa.Column('content_plan_id', sa.Uuid(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_plan_id', 'workspace_id'], ['content_plans.id', 'content_plans.workspace_id'], name='fk_content_briefs_content_plan_workspace'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], name=op.f('fk_content_briefs_plan_item_id_plan_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_briefs_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_briefs')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_content_briefs_id_workspace_id'),
    sa.UniqueConstraint('plan_item_id', name='uq_content_briefs_plan_item_id')
    )
    op.create_index(op.f('ix_content_briefs_content_plan_id'), 'content_briefs', ['content_plan_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_plan_item_id'), 'content_briefs', ['plan_item_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_public_id'), 'content_briefs', ['public_id'], unique=True)
    op.create_index(op.f('ix_content_briefs_workspace_id'), 'content_briefs', ['workspace_id'], unique=False)
    op.create_table('content_pieces',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_brief_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.String(length=1000), nullable=False),
    sa.Column('funnel_stage', sa.String(length=100), nullable=False),
    sa.Column('cta', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PRODUCTION', 'PRODUCED', 'READY_FOR_REVIEW', 'REVISION_REQUESTED', 'APPROVED', 'READY_FOR_DISTRIBUTION', 'DISTRIBUTED', 'ARCHIVED', name='content_piece_status'), server_default='DRAFT', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_brief_id', 'workspace_id'], ['content_briefs.id', 'content_briefs.workspace_id'], name='fk_content_pieces_content_brief_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_pieces_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_pieces'))
    )
    op.create_index(op.f('ix_content_pieces_content_brief_id'), 'content_pieces', ['content_brief_id'], unique=False)
    op.create_index(op.f('ix_content_pieces_public_id'), 'content_pieces', ['public_id'], unique=True)
    op.create_index(op.f('ix_content_pieces_workspace_id'), 'content_pieces', ['workspace_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('content_piece_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], name=op.f('fk_content_versions_content_piece_id_content_pieces')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_content_versions_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions'))
    )
    op.create_index(op.f('ix_content_versions_content_piece_id'), 'content_versions', ['content_piece_id'], unique=False)
    op.create_index(op.f('ix_content_versions_public_id'), 'content_versions', ['public_id'], unique=True)
    op.create_table('content_approvals',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'UNDER_REVIEW', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', 'EXPIRED', name='content_approval_status'), server_default='REQUESTED', nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], name=op.f('fk_content_approvals_content_version_id_content_versions')),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_content_approvals_reviewer_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_approvals'))
    )
    op.create_index(op.f('ix_content_approvals_content_version_id'), 'content_approvals', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_content_approvals_public_id'), 'content_approvals', ['public_id'], unique=True)
    op.add_column('audit_events', sa.Column('content_brief_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('content_piece_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('content_version_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('content_approval_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_content_approval_id'), 'audit_events', ['content_approval_id'], unique=False)
    op.create_index(op.f('ix_audit_events_content_brief_id'), 'audit_events', ['content_brief_id'], unique=False)
    op.create_index(op.f('ix_audit_events_content_piece_id'), 'audit_events', ['content_piece_id'], unique=False)
    op.create_index(op.f('ix_audit_events_content_version_id'), 'audit_events', ['content_version_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_content_brief_id_content_briefs'), 'audit_events', 'content_briefs', ['content_brief_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_content_piece_id_content_pieces'), 'audit_events', 'content_pieces', ['content_piece_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_content_version_id_content_versions'), 'audit_events', 'content_versions', ['content_version_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_content_approval_id_content_approvals'), 'audit_events', 'content_approvals', ['content_approval_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_events_content_approval_id_content_approvals'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_content_version_id_content_versions'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_content_piece_id_content_pieces'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_content_brief_id_content_briefs'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_content_version_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_content_piece_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_content_brief_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_content_approval_id'), table_name='audit_events')
    op.drop_column('audit_events', 'content_approval_id')
    op.drop_column('audit_events', 'content_version_id')
    op.drop_column('audit_events', 'content_piece_id')
    op.drop_column('audit_events', 'content_brief_id')
    op.drop_index(op.f('ix_content_approvals_public_id'), table_name='content_approvals')
    op.drop_index(op.f('ix_content_approvals_content_version_id'), table_name='content_approvals')
    op.drop_table('content_approvals')
    op.drop_index(op.f('ix_content_versions_public_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_piece_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_pieces_workspace_id'), table_name='content_pieces')
    op.drop_index(op.f('ix_content_pieces_public_id'), table_name='content_pieces')
    op.drop_index(op.f('ix_content_pieces_content_brief_id'), table_name='content_pieces')
    op.drop_table('content_pieces')
    op.drop_index(op.f('ix_content_briefs_workspace_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_public_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_plan_item_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_content_plan_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    # ### end Alembic commands ###
    # Moved after `content_briefs` is dropped — its composite FK
    # (fk_content_briefs_content_plan_workspace) depends on this
    # candidate key, so Postgres refuses to drop the constraint first.
    op.drop_constraint('uq_content_plans_id_workspace_id', 'content_plans', type_='unique')
    # `op.drop_table('content_approvals')`/`op.drop_table('content_pieces')`
    # above do not drop the native Postgres ENUM types those columns
    # implicitly created — without this, a downgrade-then-upgrade round
    # trip fails with `DuplicateObject: type "..." already exists` (the
    # same gotcha fixed in every prior migration in this project — see
    # 5e50463be153's own downgrade() for `hypothesis_status`).
    sa.Enum(name="content_approval_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="content_piece_status").drop(op.get_bind(), checkfirst=True)
