"""add tracking persistence

Revision ID: d2af7df6e279
Revises: 448a7fa7936d
Create Date: 2026-09-10 15:41:51.196340

`op.drop_table('tracking_plans')` below does not drop the native Postgres
ENUM type that column implicitly created — without the explicit drop at
the end of downgrade(), a downgrade-then-upgrade round trip fails with
`DuplicateObject: type "tracking_readiness_status" already exists` (the
same gotcha fixed in every prior migration in this project with a native
enum — see 448a7fa7936d's own downgrade() for `learning_candidate_status`).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2af7df6e279'
down_revision: Union[str, Sequence[str], None] = '448a7fa7936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_plans',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_DEFINED', 'REQUIREMENTS_DEFINED', 'CONFIGURATION_PENDING', 'CONFIGURED', 'VERIFICATION_PENDING', 'FAILED_VERIFICATION', 'CERTIFIED', name='tracking_readiness_status'), server_default='NOT_DEFINED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id', 'workspace_id'], ['campaigns.id', 'campaigns.workspace_id'], name='fk_tracking_plans_campaign_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tracking_plans_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_plans')),
    sa.UniqueConstraint('campaign_id', 'workspace_id', name='uq_tracking_plans_campaign_workspace')
    )
    op.create_index(op.f('ix_tracking_plans_campaign_id'), 'tracking_plans', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_tracking_plans_public_id'), 'tracking_plans', ['public_id'], unique=True)
    op.create_index(op.f('ix_tracking_plans_workspace_id'), 'tracking_plans', ['workspace_id'], unique=False)
    op.create_table('tracking_requirements',
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('tracking_plan_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tracking_plan_id'], ['tracking_plans.id'], name=op.f('fk_tracking_requirements_tracking_plan_id_tracking_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_requirements'))
    )
    op.create_index(op.f('ix_tracking_requirements_public_id'), 'tracking_requirements', ['public_id'], unique=True)
    op.create_index(op.f('ix_tracking_requirements_tracking_plan_id'), 'tracking_requirements', ['tracking_plan_id'], unique=False)
    op.add_column('audit_events', sa.Column('tracking_plan_id', sa.Uuid(), nullable=True))
    op.add_column('audit_events', sa.Column('tracking_requirement_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_events_tracking_plan_id'), 'audit_events', ['tracking_plan_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tracking_requirement_id'), 'audit_events', ['tracking_requirement_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_tracking_requirement_id_tracking_requirements'), 'audit_events', 'tracking_requirements', ['tracking_requirement_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_events_tracking_plan_id_tracking_plans'), 'audit_events', 'tracking_plans', ['tracking_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_events_tracking_plan_id_tracking_plans'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_events_tracking_requirement_id_tracking_requirements'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_tracking_requirement_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tracking_plan_id'), table_name='audit_events')
    op.drop_column('audit_events', 'tracking_requirement_id')
    op.drop_column('audit_events', 'tracking_plan_id')
    op.drop_index(op.f('ix_tracking_requirements_tracking_plan_id'), table_name='tracking_requirements')
    op.drop_index(op.f('ix_tracking_requirements_public_id'), table_name='tracking_requirements')
    op.drop_table('tracking_requirements')
    op.drop_index(op.f('ix_tracking_plans_workspace_id'), table_name='tracking_plans')
    op.drop_index(op.f('ix_tracking_plans_public_id'), table_name='tracking_plans')
    op.drop_index(op.f('ix_tracking_plans_campaign_id'), table_name='tracking_plans')
    op.drop_table('tracking_plans')
    # ### end Alembic commands ###
    sa.Enum(name="tracking_readiness_status").drop(op.get_bind(), checkfirst=True)
