import Link from "next/link";
import { campaigns, stats } from "@/lib/dashboard-data";
import { Icon, type IconName } from "@/components/ui/icon";
import { PreviewButton } from "@/components/ui/preview-button";

export function Dashboard() {
  return <div className="dashboard">
    <div className="page-heading"><div><div className="eyebrow"><span /> TU CENTRO DE CRECIMIENTO</div><h1>Buenas tardes, Emilia <span className="greeting-spark" aria-hidden="true">✦</span></h1><p>Gestiona tus campañas y contenidos con inteligencia artificial.</p></div><Link href="/campaigns/new" className="button primary"><Icon name="plus" size={18} />Nueva campaña</Link></div>
    <div className="demo-notice"><span className="demo-pill">DEMO</span> Estás explorando tu espacio con datos de ejemplo. <span className="demo-note">Las acciones estarán disponibles próximamente.</span></div>
    <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><span className="hero-label"><Icon name="spark" size={16} /> GRANDES IDEAS. NUEVAS POSIBILIDADES.</span><h2 id="hero-title">Tu próxima campaña<br />empieza con una idea.</h2><p>Tú pones la visión. La inteligencia artificial te ayuda<br className="desktop-break" /> a convertirla en una estrategia con impacto.</p><Link href="/campaigns/new" className="button hero-button">Dale vida a tu idea <Icon name="arrow" size={17} /></Link></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="art-core"><Icon name="spark" size={49} /></div><div className="floating-card strategy"><span className="art-icon"><Icon name="target" /></span><div><strong>Estrategia con propósito</strong><span>Una dirección clara para crecer</span></div><span className="tiny-check">✓</span></div><div className="floating-card idea"><span className="art-icon"><Icon name="content" /></span><div><strong>Ideas que conectan</strong><span>Contenido con tu esencia</span></div></div><span className="art-star star-one">✦</span><span className="art-star star-two">✧</span><span className="art-dot" /></div></section>
    <section aria-labelledby="overview-title"><div className="section-heading"><h2 id="overview-title">Tu actividad, de un vistazo</h2><span className="period"><Icon name="calendar" size={15} /> Últimos 30 días</span></div><div className="stats-grid">{stats.map(stat => <article className="stat-card" key={stat.label}><div className="stat-top"><span>{stat.label}</span><span className={`icon-tile ${stat.tone}`}><Icon name={stat.icon} size={19} /></span></div><div className="stat-value-row"><strong className="stat-value">{stat.value}</strong><div className={`mini-bars ${stat.tone}`} aria-hidden="true">{stat.bars.map((height, i) => <span key={i} style={{ height: `${height}%` }} />)}</div></div><p className="stat-change"><span>↗ {stat.change}</span> vs. mes anterior</p></article>)}</div></section>
    <div className="detail-grid"><section className="panel campaigns" aria-labelledby="campaigns-title"><div className="panel-heading"><div><h2 id="campaigns-title">Campañas recientes</h2><p>De una buena idea a grandes resultados.</p></div><Link href="/campaigns" className="text-button">Ver todas <Icon name="arrow" size={15} /></Link></div><div className="campaign-list">{campaigns.map(campaign => <article className="campaign-row" key={campaign.id}><div className="campaign-main"><span className={`campaign-avatar ${campaign.tone}`}>{campaign.initials}</span><div><h3>{campaign.name}</h3><p>{campaign.category}</p></div><Link href={campaign.workspaceHref ?? "/campaigns"} className="icon-button campaign-action" aria-label={campaign.workspaceHref ? `Abrir ${campaign.name}` : `Ver campañas: ${campaign.name}`}><Icon name="chevron" size={17} /></Link></div><div className="campaign-details"><span className={`status ${campaign.status === "Activa" ? "success" : campaign.status === "Borrador" ? "draft" : "warning"}`}><span />{campaign.status}</span><div className="progress-group"><progress max={100} value={campaign.progress} aria-label={`Progreso de ${campaign.name}`} /><span>{campaign.progress}%</span></div><time dateTime={campaign.date}>{campaign.dateLabel}</time></div></article>)}</div><div className="campaign-footer"><span className="live-dot" /> Un espacio para cada idea. Una visión para todas.</div></section>
    <section className="panel ai-panel" aria-labelledby="ai-title"><div className="panel-heading"><div className="ai-title"><span className="icon-tile blue"><Icon name="spark" /></span><h2 id="ai-title">Actividad de IA</h2></div><span className="example-tag">Ejemplo</span></div><p className="ai-description">Así toma forma tu próxima campaña.</p><div className="ai-campaign"><span className="live-dot" />Método Canino en Casa</div><ol className="activity-list">{[{ title: "Mercado analizado", detail: "Oportunidades encontradas", state: "done" }, { title: "Audiencia identificada", detail: "Conocemos a quién conectar", state: "done" }, { title: "Estrategia en desarrollo", detail: "Conectando las piezas", state: "current" }, { title: "Contenido pendiente", detail: "El siguiente paso de tu idea", state: "pending" }].map(item => <li className={item.state} key={item.title}><span className="activity-marker" aria-hidden="true">{item.state === "done" ? <Icon name="check" size={13} /> : item.state === "current" ? "●" : "○"}</span><div><h3>{item.title}</h3><p>{item.detail}</p></div></li>)}</ol><div className="ai-footer"><Icon name="spark" size={15} /> Tú imaginas. Las ideas avanzan.</div></section></div>
    <section aria-labelledby="quick-title"><div className="section-heading"><h2 id="quick-title">¿Qué quieres hacer hoy?</h2><span className="muted small-text">Tu siguiente paso, a un clic</span></div><div className="quick-grid">{([{ title: "Nueva campaña", text: "Dale forma a tu próxima idea", icon: "plus", tone: "blue" }, { title: "Crear contenido", text: "Conecta con tu audiencia", icon: "content", tone: "violet" }, { title: "Ver métricas", text: "Descubre qué está funcionando", icon: "chart", tone: "mint" }, { title: "Planificar calendario", text: "Organiza lo que viene", icon: "calendar", tone: "orange" }] satisfies { title: string; text: string; icon: IconName; tone: string }[]).map(action => action.title === "Nueva campaña" ? <Link href="/campaigns/new" className="quick-card" key={action.title}><span className={`icon-tile ${action.tone}`}><Icon name={action.icon} /></span><span><strong>{action.title}</strong><span>{action.text}</span></span><Icon name="chevron" size={15} /></Link> : <PreviewButton className="quick-card" key={action.title}><span className={`icon-tile ${action.tone}`}><Icon name={action.icon} /></span><span><strong>{action.title}</strong><span>{action.text}</span></span><Icon name="chevron" size={15} /></PreviewButton>)}</div></section>
    <footer className="dashboard-footer"><span>Hecho para ideas que merecen crecer.</span><span>Impulso <span aria-hidden="true">✦</span> Tu creatividad, más lejos.</span></footer>
  </div>;
}
